### ISSUE TITLE
pack don't load

### ISSUE THREAD

**Issue by janbildsoehansen** [workingDog/AgroApiExample#1]
your Agro API don't work it gives a error when you try to import it to a project it says  : 
because every version of AgroAPI contains incompatible tools version and root depends on AgroAPI 0.1.2..<1.0.0, version solving failed.

**Comment by workingDog** [comment]
thanks for letting me know. I'll investigate, it maybe to do with swift-tools-version:5.3
instead of 5.2 in Package.swift.

I'll test a few ideas.

**Comment by janbildsoehansen** [comment]
im not sure im quiet new to coding :D

**Comment by workingDog** [comment]
I've created a new version:  AgroAPI 0.1.3.
Could you try it please.

**Comment by janbildsoehansen** [comment]
works now
